Traceback (most recent call last):
  File "/home/robot/WRO-Buonarr-2021/ev3_message/main.py", line 21, in <module>
  File "/home/robot/WRO-Buonarr-2021/ev3_message/main.py", line 18, in main
  File "/home/robot/WRO-Buonarr-2021/ev3_message/LocalLib/messages.py", line 24, in client
AttributeError: 'function' object has no attribute 'connect'
